### ISSUE TITLE
the inference results is wrong after training

### ISSUE THREAD

**Issue by chengqi0514** [sherwinbahmani/tc4d#2] opened 2024-04-06 10:17 UTC
The inference video:

https://github.com/sherwinbahmani/tc4d/assets/50334715/69719fbd-60c5-4f28-a46d-3d0ee4b1e9fd

The training video:

https://github.com/sherwinbahmani/tc4d/assets/50334715/f08683bc-4f98-4d58-83f1-94f00a0c8150

When after training, I use the following code to render videos
```sh
# Render high resolution videos used in the paper and project page after training
ckpt=/path/to/tc4d_stage_3/a_deer_walking@timestamp/ckpts/last.ckpt
python launch.py --config configs/tc4d_stage_3_eval.yaml --test --gpu $gpu exp_root_dir=$exp_root_dir seed=$seed system.prompt_processor.prompt="a deer walking" system.scene_setup_path=$scene_setup_path system.weights=$ckpt
```

but the results is different from the video during training. The object does't move.

**Comment by sherwinbahmani** [comment] 2024-04-06 13:57
Hi,

You are right, can you remove this line from the config and check again: https://github.com/sherwinbahmani/tc4d/blob/7f228929797daaffd01fa4baf9120cf5ef286a64/configs/tc4d_stage_3_eval.yaml#L74

Edit: I pushed the fix

**Comment by sherwinbahmani** [comment] 2024-04-10 14:37
I guess this issue is solved. Please reopen, if the issue is not solved!

**Closed as completed by sherwinbahmani** 2024-04-10 14:37 UTC
